# Generated by Django 4.2.5 on 2023-10-13 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value_unit', models.CharField(max_length=100, verbose_name='Величина')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='reciepts/images/')),
                ('timing', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Обозначте время приготовления')], verbose_name='Время приготовления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciept', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Слаг')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'unique_together': {('name', 'color', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('reciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to='reciepts.reciept', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Обозначте ингридиенты для рецепта')], verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepts.ingredient')),
                ('reciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list', to='reciepts.reciept')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
            },
        ),
        migrations.AddField(
            model_name='reciept',
            name='ingredients',
            field=models.ManyToManyField(related_name='reciepts', through='reciepts.Routing', to='reciepts.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='reciept',
            name='tags',
            field=models.ManyToManyField(related_name='reciept', to='reciepts.tags', verbose_name='Тэги'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('reciept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='reciepts.reciept', verbose_name='Рецепт - избранное')),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('author', 'reciept'), name='unique_shopping_list'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('reciept', 'author'), name='unique_author_favorite'),
        ),
    ]
