# Generated by Django 4.2.5 on 2023-10-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciepts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
