# Generated by Django 4.2.5 on 2023-10-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciepts', '0002_alter_favorite_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='description',
            new_name='text',
        ),
    ]
