# Generated by Django 4.2.5 on 2023-10-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciepts', '0003_rename_description_reciept_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='timing',
            new_name='cooking_time',
        ),
    ]
