# Generated by Django 4.2.5 on 2023-10-18 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepts', '0004_rename_timing_reciept_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciept',
            options={'ordering': ('-id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Обозначте время приготовления')], verbose_name='Время приготовления'),
        ),
    ]
